### ISSUE TITLE
Crashes with not enough memory after long periods of usage

### ISSUE THREAD

**Issue by Makpptfox** [stoneharry/WoW-Spell-Editor#58] opened 2019-02-01 04:35 UTC
Hi,

I had this issue several times now since I use the version 1.8.0 of your editor (French locale, 64bits version) :

When I just do what the editor is made for, aka creating spells, after switching between tabs, spells and saving a certain amount of times (heavy usage for like 40minutes) it suddenly freezes and dissapear and I have to kill it's task manually.

The error log only say "Not enough memory" but I had only 67% of my total memory used while the Editor was launched and crashed and the last 10 lines of the debug_output only talk about an unexpected token in the description field.

```
Unexpected tokens [$m1, REFERENCE] PLUS [$AP, REFERENCE]
Unexpected tokens [$AP, REFERENCE] MULTIPLY [0, NUMBER]
> Token '$m1' derived value '$m1'
> Token '+' derived value ''
> Token '$AP' derived value '$AP'
> Token '*' derived value ''
> Token '0' derived value '0'
${$m1+$AP*0.1}	----	Processing
Token: [$m1, REFERENCE, $m1]
Token: [+, PLUS, ]
Token: [$AP, R
```

I can't really tell you how to reproduce this issue tbh, it happen randomly after many reload/saves, therefore I'm not really waiting for a "fix" but I just assumed you would like to know anyway this issue eventually existed.

**Comment by stoneharry** [comment] 2019-02-01 13:05
The unexpected token is because $AP tag is not supported as the context of a player is required to work out attack power.

It sounds like a memory leak is causing the crash after long periods of usage - this is pretty low priority since restarting the app will fix it.

**Comment by Makpptfox** [comment] 2019-02-01 17:43
I do for 90% of the time create/modifying/saving spells. In 4 crashes I haven't imported/exported nor deleted any spells.

Thing is, it may be because of the icons loading, I have a lot of them (12k+) in my interface folder, each time I create a new spell, it seems like every icons in the list of the main menu are reloading and the "crash" happened after a new spell was created or the spells changes were saved nearly everytime.

**Comment by stoneharry** [comment] 2019-02-13 19:48
@Makpptfox Any chance you can share your icons and SpellIcon.dbc with me so that I can run some tests with it?

**Comment by Makpptfox** [comment] 2019-02-14 19:39
Here it is. https://mega.nz/#!0UUDQQYR!OYihyBwcYsbZ0ogPM4f19QWYojbKFuTI2m_rN2Ouw-0

**Comment by stoneharry** [comment] 2019-02-25 20:01
It's scrolling on the spell selection list causing the memory leak. I am debugging it, but all I'm able to reproduce currently is it is constantly recreating its contents and not garbage collecting the old entries. New stack panels + images + textboxes mostly after comparing two heap dumps:

![Stack comparison](https://i.imgur.com/upU6HCb.png)

**Comment by stoneharry** [comment] 2019-02-25 20:21
```c#
private static volatile uint SpellListLoadedCount = 0;

        private void IsSpellListEntryVisibileChanged(object o, DependencyPropertyChangedEventArgs args)
        {
            var image = o as Image;
            if (!(bool)args.NewValue)
            {
                --SpellListLoadedCount;
                image.Source = null;
                return;
            }
            else
                ++SpellListLoadedCount;
            var text = ((TextBlock)(((StackPanel)image.Parent).Children[1])).Text;
            Console.WriteLine($"Updating {text}\t{args.NewValue}\tLoaded: {SpellListLoadedCount}");
            var iconId = uint.Parse(image.ToolTip.ToString());
            var filePath = loadIcons.GetIconPath(iconId) + ".blp";
            try
            {
                using (var fileStream = new FileStream(filePath, FileMode.Open))
                {
                    using (var blpImage = new SereniaBLPLib.BlpFile(fileStream))
                    {
                        using (var bit = blpImage.getBitmap(0))
                        {
                            image.Source = System.Windows.Interop.Imaging.CreateBitmapSourceFromHBitmap(
                                bit.GetHbitmap(), IntPtr.Zero, Int32Rect.Empty,
                                BitmapSizeOptions.FromWidthAndHeight(bit.Width, bit.Height));
                            //image.UpdateLayout();
                        }
                    }
                }
            }
            catch (Exception)
            {
                Console.WriteLine($"[SpellSelectList] WARNING Unable to load image: {filePath}");
            }
        }
```
Scrolling a couple of times:
```
Updating  26424 - Green Rocket Cluster	True	Loaded: 2328
Updating  26425 - Red Rocket Cluster	True	Loaded: 2329
Updating  26426 - Large Blue Rocket Cluster	True	Loaded: 2330
Updating  26427 - Large Green Rocket Cluster	True	Loaded: 2331
Updating  26428 - Large Red Rocket Cluster	True	Loaded: 2332
Updating  26578 - Stealth 3	True	Loaded: 2333
Updating  26609 - Black Diamond Crab	True	Loaded: 2334
```

Wayyyy too many objects still loaded. Doesn't explain the new text boxes though, it should only be the image property updating.

**Comment by stoneharry** [comment] 2019-02-25 21:24
I experimented creating the entire list instead of trying to load/unload the images. It runs out of memory doing this. Seems I need to rework the way we load data on this list.

**Comment by stoneharry** [comment] 2019-03-13 19:16
Further debugging:

The spell selection list is a list of stack panels. Inside each stack panel is a TextBlock and a Image for displaying the spell name and icon.

The ListBox is created with the following properties:
```
                             VirtualizingStackPanel.IsVirtualizing="True"
                             VirtualizingStackPanel.VirtualizationMode="Recycling"
                             ScrollViewer.IsDeferredScrollingEnabled="True"
```

In the following experiment I load 5000 rows fully by loading the icon and setting it in the UI.

After I try to clear the icon on those 5000 rows, which I do see in the UI. However even after calling a GC collect it will not free the memory.

```C#
                // GC Experiment
                Console.WriteLine("GC Experiment");
                foreach (var obj in SelectSpell.Items)
                {
                    var panel = obj as StackPanel;
                    var image = panel.Children[0] as Image;
                    var iconId = uint.Parse(image.ToolTip.ToString());
                    var filePath = loadIcons.GetIconPath(iconId) + ".blp";
                    try
                    {
                        using (var fileStream = new FileStream(filePath, FileMode.Open))
                        {
                            using (var blpImage = new SereniaBLPLib.BlpFile(fileStream))
                            {
                                using (var bit = blpImage.getBitmap(0))
                                {
                                    image.Source = System.Windows.Interop.Imaging.CreateBitmapSourceFromHBitmap(
                                        bit.GetHbitmap(), IntPtr.Zero, Int32Rect.Empty,
                                        BitmapSizeOptions.FromWidthAndHeight(bit.Width, bit.Height));
                                    ++count;
                                    if (count == 5000)
                                        break;
                                }
                            }
                        }
                    }
                    catch (Exception)
                    {
                        Console.WriteLine($"[SpellSelectList] WARNING Unable to load image: {filePath}");
                    }
                }
                Console.WriteLine("Clearing GC");
                foreach (var obj in SelectSpell.Items)
                {
                    var panel = obj as StackPanel;
                    var image = panel.Children[0] as Image;
                    image.Source = null;
                }
                GC.Collect();
                Console.WriteLine("Done.");
```

**Comment by stoneharry** [comment] 2019-03-14 22:29
Cromon referred me to some documentation that describes what I am doing wrong: https://docs.microsoft.com/en-us/dotnet/api/system.drawing.bitmap.gethbitmap?view=netframework-4.7.2

I need to call `DeleteObject` passing the bitmap pointer manually to garbage collect the object.

**Comment by stoneharry** [comment] 2019-03-17 16:58
Reopening this issue to get feedback on the changes made in pull request #79 . This will be available in the next release.

**Comment by stoneharry** [comment] 2019-03-17 17:10
Release build v1.8.5 - let me know how it goes with this one.

**Comment by stoneharry** [comment] 2019-03-18 19:32
Now it crashes when creating/deleting spells, it works but you have to restart the program. 😅 This is why unit tests would be great, but the project is far too archaic to do that easily.

Fixed in 02730cda08e00ab5662f29484b3cdc13d24356ce which also brings another big performance improvement.

**Comment by stoneharry** [comment] 2019-03-18 19:45
I think all memory leaks are resolved now. A lot of memory can still be used (~1GB) if you have opened and browsed most of the spell selection list as well as the icon tab. This is because they are not currently sharing the same image sources, they both load their own copies into memory.

**Comment by stoneharry** [comment] 2019-03-19 19:50
Release build v1.8.6 seems pretty stable and contains many more performance improvements. Let me know how it goes.

**Comment by stoneharry** [comment] 2019-07-02 16:12
Closing with the release of v1.8.7. Please reopen or create a new issue if you think there is still an issue.

**Closed by stoneharry** 2019-07-02 16:12 UTC
Labels: bug
