### ISSUE TITLE
List spells recursively rather than listing all at the same time

### ISSUE THREAD

**Issue by mmlTools** [stoneharry/WoW-Spell-Editor#62] opened 2019-02-02 18:43 UTC
The program load time is really slow due to listing all icons and spells at the same time creating a huge list. Add a on scroll event to load spells from the last loaded item and create a new config item to set how many items are loaded / session. 

SELECT * FROM $DATABASE.$TABLE ORDER BY ID ASC LIMIT $LAST_ITEM, $ITEMS_TO_LOAD;

this should improve the loading time a little

**Comment by stoneharry** [comment] 2019-02-09 19:29
The main cost is actually loading the DBC files into memory. The database query and population of the UI elements takes a fraction of the time in my environment, but I am using a SSD querying a local database.

The former can be improved I suspect by reworking the string block reading, and the latter as you said.

How long are the steps taking for you? It does need improving but I'm not sure how high priority to make this.

**Comment by mmlTools** [comment] 2019-02-10 09:02
it takes about 30-40 seconds to load all the spells, i'm not using SSD and haven't tested on one

**Comment by stoneharry** [comment] 2019-02-16 15:36
The spell selection list is actually already paged:

```c#
        private DataRowCollection GetSpellNames(UInt32 lowerBound, UInt32 pageSize, int locale)
        {
			DataTable newSpellNames = adapter.Query(string.Format(@"SELECT `id`,`SpellName{1}`,`SpellIconID` FROM `{0}` ORDER BY `id` LIMIT {2}, {3}",
                 config.Table, locale, lowerBound, pageSize));

            spellTable.Merge(newSpellNames, false, MissingSchemaAction.Add);

            return newSpellNames.Rows;
        }
```

It doesn't take that much memory to keep them all loaded so it's no problem for querying for it all rather than waiting for page up/page down. The issue seems to be that this operation should be asynchronous. For the icons I agree that needs to be paged.

**Comment by stoneharry** [comment] 2019-02-17 17:04
I have been doing some performance analysis, it looks like updating the spell selection list is happening on the UI thread causing a big slow down.

```
Loaded AreaTable.dbc into memory in 22ms. Records: 11ms, strings: 11ms
Loaded SpellCategory.dbc into memory in 0ms. Records: 0ms, strings: 0ms
Loaded SpellDispelType.dbc into memory in 0ms. Records: 0ms, strings: 0ms
Loaded SpellMechanic.dbc into memory in 0ms. Records: 0ms, strings: 0ms
Loaded SpellFocusObject.dbc into memory in 1ms. Records: 0ms, strings: 1ms
Loaded AreaGroup.dbc into memory in 0ms. Records: 0ms, strings: 0ms
Loaded SpellDifficulty.dbc into memory in 0ms. Records: 0ms, strings: 0ms
Loaded SpellCastTimes.dbc into memory in 0ms. Records: 0ms, strings: 0ms
Loaded SpellDuration.dbc into memory in 0ms. Records: 0ms, strings: 0ms
Loaded SpellRange.dbc into memory in 0ms. Records: 0ms, strings: 0ms
Loaded SpellRadius.dbc into memory in 0ms. Records: 0ms, strings: 0ms
Loaded ItemClass.dbc into memory in 0ms. Records: 0ms, strings: 0ms
Loaded ItemSubClass.dbc into memory in 0ms. Records: 0ms, strings: 0ms
Loaded TotemCategory.dbc into memory in 0ms. Records: 0ms, strings: 0ms
Loaded SpellRuneCost.dbc into memory in 0ms. Records: 0ms, strings: 0ms
Loaded SpellIcon.dbc into memory in 19ms. Records: 3ms, strings: 16ms
Loaded SpellDescriptionVariables.dbc into memory in 0ms. Records: 0ms, strings: 0ms
Worker progress change event took 6ms to handle
Worker progress change event took 355ms to handle
Worker progress change event took 343ms to handle
Worker progress change event took 356ms to handle
Worker progress change event took 365ms to handle
Worker progress change event took 343ms to handle
Worker progress change event took 357ms to handle
Worker progress change event took 355ms to handle
Worker progress change event took 342ms to handle
Worker progress change event took 359ms to handle
Worker progress change event took 375ms to handle
Loaded spell selection list contents in 6899ms
```

**Comment by mmlTools** [comment] 2019-02-17 17:19
so when saving a spell, system is restoring the the whole loading process ? Why not making it 2 way save the query in database and update the spells map rather than reloading the whole thing?

**Comment by stoneharry** [comment] 2019-02-17 17:22
> so when saving a spell, system is restoring the the whole loading process ? Why not making it 2 way save the query in database and update the spells map rather than reloading the whole thing?

It's done that way by design. If you are using MySQL and have many people working on the same table at the same time, then reloading all changes is the only way to ensure you have the latest data. It is only loading a subset of the data: id, spellName, and spellIcon. It does not load every single entire row into memory, only the row you have currently selected is fully loaded.

**Comment by stoneharry** [comment] 2019-02-17 17:34
c8257f8 greatly improves the performance of the UI while the spell selection list is refreshing. There are still a lot of improvements that can be made but this makes it a bit more bearable.

**Comment by mmlTools** [comment] 2019-02-17 17:35
well it's still not 100% safe what if 2 users modify the same spell at the same time ? you can create another table for ongoing updates/edits with the following structure, spellid, action_type
ACTION_TYPE_1 = 0 // user just selected the spell -> Notify every other users about this
ACTION_TYPE_2 = 1 // user is creating a new spell with id = spellid -> other users can't create another spell with that id
ACTION_TYPE_3 = 2 // user just saved spellid -> save spell in database -> program is ready to reload data I have many ideas on how this program can be improved add me on discord if you want Darksoke#0206

**Comment by stoneharry** [comment] 2019-02-17 17:41
There are a great many things we could add to this program. The question is what is actually worth implementing? Do we actually need better collision detection if the people using this program are in teams of < 5 people?

And how do we notify other users? We don't have a connection to other users, only to the database. We could have a table that stores edit action logs with timestamps, then the program periodically queries this database and operates on any changes it hasn't seen. Occasionally this table would need to be purged of old data.

I will add you to Discord but I would prefer any ideas/bugs/enhancements to be tracked through the Issue Tracker here.

**Comment by stoneharry** [comment] 2019-02-23 15:12
I am rewriting how images are used in the program. I have got the icon tab loading in 227ms now. Brings down the memory usage a fair bit too.

**Comment by stoneharry** [comment] 2019-03-19 19:50
Please test v1.8.6 and let me know how that performs. I have made a lot of performance optimisations.

**Comment by stoneharry** [comment] 2019-07-02 16:12
Closing with the release of v1.8.7. Please reopen or create a new issue if you think there is still an issue.

**Closed by stoneharry** 2019-07-02 16:12 UTC
Labels: enhancement
