### ISSUE TITLE
Russian localization

### ISSUE THREAD

**Issue by MrSnike** [stoneharry/WoW-Spell-Editor#106] opened 2020-04-22 11:06 UTC
Do you plan to make Russian localization in the program?

**Comment by stoneharry** [comment] 2020-04-22 16:23
I don't speak Russian. The best I can do is run it through Google translate.

Please feel free to contribute any translations, all you need to do is create a new language XAML file. :)

**Comment by MrSnike** [comment] 2020-04-23 10:36
Yes The Russian client DBC files are supported, but does not display table contents spell name, spell rank, spell tooltip ....
![Screenshot_50](https://user-images.githubusercontent.com/41971553/80089916-5c9adc80-8567-11ea-80de-d89f622cb8d7.png)

**Comment by stoneharry** [comment] 2020-04-23 11:04
Did you update all the DBC files, or just the spell.dbc? Mixed locale does not work well as tracked in #55.

Can you upload your DBC files for me to test with please? Then I can debug why it might not be working.

**Comment by MrSnike** [comment] 2020-04-23 11:52
I changed all dbc files from the original game client, but the problem still remained.
[DBC_335_wotlk.zip](https://github.com/stoneharry/WoW-Spell-Editor/files/4522269/DBC_335_wotlk.zip)

**Comment by stoneharry** [comment] 2020-04-23 20:16
Thank you - I'll take a look over the weekend.

**Comment by stoneharry** [comment] 2020-04-25 10:06
I have reproduced this bug, likely introduced in ~v1.9.0. It looks like the data is loaded into the database correctly but not displayed on the user interface:

![screenshot](https://i.imgur.com/cZcdpxZ.png)

**Comment by stoneharry** [comment] 2020-04-25 10:14
Fixed in b2c8df228dedaa2c485e2c112f465ec901b986e8.

![screenshot](https://i.imgur.com/gVw2hkh.png)

Looks like it was only the Russian locale broken. 😅 I'll leave this issue open until a new release is published.

**Comment by stoneharry** [comment] 2020-04-25 10:42
Fixed in v1.9.4 - closing.

**Closed by stoneharry** 2020-04-25 10:42 UTC
Labels: bug, question

**Comment by MrSnike** [comment] 2020-04-26 12:06
Thank you so much
