### ISSUE TITLE
Information in list does not match information in db

### ISSUE THREAD

**Issue by itswicky** [stoneharry/WoW-Spell-Editor#220] opened 2023-09-12 04:23 UTC
**Spell editor version**
2.2.0

**Describe the bug**
When saving a spell, spells created by copying another spell during that session will appear to have incorrect information in the spell editor, although their data is saved properly in the db.

**To Reproduce**
1. Create a copy of an existing spell.
2. Edit the newly created spell.
3. Create another new spell and save changes to it.
4. Your previously created spell will have it's old icon and name appear in the list, but will have proper information in db.

**Expected behavior**
Spells show in list should have information matching what is in db.

**Screenshots**
![bug_report](https://github.com/stoneharry/WoW-Spell-Editor/assets/28546681/2248f20f-8bc4-48f4-bc60-c65c3fbc8972)

**Additional Information**
I assume this is related to not doing full table queries after creating new spells.

**Comment by itswicky** [comment] 2023-09-12 04:23
You cannot tell in the SS provided, but the icon for 91262 has also been changed. Again, db has correct information, but list does not display it properly.

**Comment by stoneharry** [comment] 2023-09-12 14:25
Duplicate of #216 

It's a purely visual bug, selecting the spell shows the right info. I do need to reproduce and fix it though.

**Comment by stoneharry** [comment] 2024-01-16 22:38
Fixed with v.2.2.1.

**Closed by stoneharry** 2024-01-16 22:38 UTC
Labels: bug
