### ISSUE TITLE
Remorseless Winter Visual Tab Bug

### ISSUE THREAD

**Issue by Sanctuary1** [stoneharry/WoW-Spell-Editor#155] opened 2021-11-27 23:34 UTC
Good afternoon. All Remorseless Winter spells show a bug report when clicking the Visual tab.
![image](https://user-images.githubusercontent.com/26613312/143723413-fea0ba28-c146-4669-a54d-544d5f29bbc8.png)

**Comment by stoneharry** [comment] 2021-11-27 23:43
Confirmed, this is very easy to reproduce.

**Comment by stoneharry** [comment] 2021-12-05 16:08
Fixed the error occuring in the UI with 31a7853196c854da24251449846919030d52e924, but this only fixes the display of the data. The root cause of the issue is that the `AttachmentId` column for the `SpellVisualKitModelAttach` table is stored as a uint rather than a int (-1 is used to signify no attachment ID).

To support this would be a breaking change and to handle the special value (-1) in the program. I'll leave this open to track doing this work.

**Comment by stoneharry** [comment] 2021-12-13 21:34
Release Build 2.0 has been pushed, closing this.

**Closed by stoneharry** 2021-12-13 21:34 UTC
Labels: bug
